# Generated by Django 5.2 on 2025-07-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_client_expedition_poisson_vehicule_user_actif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('COMPTABLE', 'Comptable'), ('GESTIONNAIRE', 'Gestionnaire')], default='USER', max_length=15),
        ),
    ]
